language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
services:
  - xvfb
before_install:
  - "export DISPLAY=:99.0"
cache: pip
# command to install dependencies
install:
  - pip install -U setuptools
  - pip install Cython --install-option="--no-cython-compile"
  - pip install -e .
  # - pip install -r requirements.txt
# command to run tests
script: nosetests
